name: update PR D-n Labels
on:
  schedule:
    - cron: '35 13 * * *'
jobs:
  d-day-labeler:
    runs-on: [ubuntu-latest]
    steps:
      - name: Update D-n Labels
        uses: naver/d-day-labeler/@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
