name: Notify toss Slack about PRs

on:
  workflow_dispatch:

jobs:
  notify-slack:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 코드
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: |
          npm install @octokit/rest
          npm install axios

      - name: 찾고 슬랙으로 알림 보내기
        run: node .github/scripts/toss-noti.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
